### PR TITLE
Assignment

### PR DESCRIPTION
**Pull request by joeypohie**
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)

Adding code to complete the script

## What did you learn from the changes you have made?

How to navigate between folders using the terminal and how to use git

## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?

A more longwinded method of changing directory to each folder before each change

## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?

Got tripped up on file paths a few times. Had to create new folders to test it. Also got tripped up on pushing to Github (on a mac). Redid it a few times using help from chatgpt and google.

## How were these changes tested?

Tested through terminal

## Checklist
- [x] I can confirm that my changes are working as intended

### CODE REVIEW

**Review by anjali-deshpande-hub — CHANGES_REQUESTED** [review]
Please check the following and correct:
1. Q1 There are multiple calls to mkdir
2. Q5, Q6, Q7, Q8 The usage of cp and rm commands are correct. But, there is no need to use find and -exec options. Although you will be able to successfully; doing the task with find and exec, the downside is that its slower.

**Comment by anjali-deshpande-hub** [comment]
Please don't merge the PR or close the PR until the review is finished. Kindly, keep the PR open. When the reviewer tags the PR as approved, you can merge the code to main OR you can choose to leave it open. 

Please go over the review comments posted in the first review. Replace multiple calls to mkdir in Question 1 to just one call and res-submit. You might have to revert the merge. See 'Handling accidental merges' section of [submission ](https://github.com/UofT-DSI/onboarding/blob/main/onboarding_documents/submissions.md)guidelines

**Comment by anjali-deshpande-hub** [comment]
You are just a few step away from finishing your assignment. Please fix answer to Q1. If you need any help, please reach out to the learning support during work period or office hours. Thanks!

**Comment by joeypohie** [comment]
I think I fixed it? When I clone my assignment branch, Q1 is fixed.

**Comment by anjali-deshpande-hub** [comment]
Its likely you haven't push your local changes to the assignment branch to github. I still don't see it fixed in the branch on github. https://github.com/joeypohie/shell/blob/assignment/02_activities/assignments/assignment.sh

**Comment by joeypohie** [comment]
But if I am cloning from the assignment branch, wouldn’t that mean I should
get the version on the website?

When I make a change and check git status, it says I am up to date with the
branch.

**Comment by anjali-deshpande-hub** [comment]
**Cloning** can only be done on a **repository**, not a branch.  When you clone a repository, you are copying the entire repository (including all its branches and history) from a remote location (like GitHub) to your local machine. 
For eg: git clone https://github.com/username/repository.git 
This command creates a local copy of the entire repository, with all branches and commits, but it checks out the default branch (usually main or master) for you. 

To make sure your local branch (assignment) is up to date with the version on GitHub (i.e., it matches exactly what is on the remote repository), you can do:
git fetch origin
git checkout assignment
git reset --hard origin/assignment  **(To make your local branch match exactly what’s on GitHub - discarding local changes)**
git pull origin assignment **(To pull the latest changes from GitHub - without discarding local changes)**

Remember the best way to check if Github has your changes is to go the branch assignment (in the browser) and look at code under that branch. 
I hope this helps! Please feel free to connect during office hours and one of the learning support staff will be happy to help you,

**Comment by joeypohie** [comment]
I see - that makes sense.

I think I fixed it, but accidentally made a pull request to the DSI main.

I re-followed the steps above but it says I'm up to date with the corrected
code I pushed. And the error doesn't show up when I pull... but it's not
showing up on my repo T_T

**Pull request merged**
